# Default values for python.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  registry: docker.io
  org: santiycr
  name: cssify-web
  tag: 1.1.0
  pullPolicy: IfNotPresent
service:
  name: cssify-web
  type: NodePort
  externalPort: 80
  internalPort: 5000
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
